baseURL= https://example.com/
languageCode= id-ID
title= Root's Home
[params]
  Description= "I'm root, I am root, i am root. 😁 i am root."
disqusShortname=
theme= the-roots-home

enableGitInfo= true
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = vs
[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= goldmark
